### ISSUE TITLE
Fix association count

### ISSUE THREAD

**Issue by LaurentDeMontBlanc** [SphericalElephant/ExSeq#98]
The following route returns a 404 Error.

| Method | Relation                               |  Route                           | Permission  |
|-----------|--------------------------------------|--------------------------------|-----------------|
| GET     | HasMany / BelongsToMany | /source/:id/target/count | READ          |

**Comment by siyb** [comment]
@LaurentDeMontBlanc sorry for the late reply, is this actually still an issue?
